using System;

namespace Report.Fields.Model
{
    public class EmployeeDDM 
    {
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Address3 { get; set; }
        public string Address4 { get; set; }
        public string Address5 { get; set; }
        public DateTime? AEAutoEnrolmentDate { get; set; }
        public DateTime? AEDeferralDate { get; set; }
        public DateTime? AEEnrolmentNoticeDate { get; set; }
        public DateTime? AEEntitledNoticeDate { get; set; }
        public bool? AEIsInEligibleScheme { get; set; }
        public bool? AEIsPostponementActive { get; set; }
        public DateTime? AENonEligibleNoticeDate { get; set; }
        public DateTime? AEOptedInDate { get; set; }
        public DateTime? AEOptedOutBeforeEligibleDate { get; set; }
        public DateTime? AEOptedOutDate { get; set; }
        public DateTime? AEPostponementNoticeDate { get; set; }
        public string AnalysisCode { get; set; }
        public string BankAccountName { get; set; }
        public string BankAccountNo { get; set; }
        public string BankBranch { get; set; }
        public string BankName { get; set; }
        public string BankSortCode { get; set; }
        public string BuildingSocietyNo { get; set; }
        public DateTime? CeasedQPSMembershipDate { get; set; }
        public string ClockNo { get; set; }
        public DateTime? CompanyJoinDate { get; set; }
        public string ContactTelephone { get; set; }
        public int? ContractTypeId { get; set; }
        public int? CostCode10Id { get; set; }
        public double? CostCode10Percentage { get; set; }
        public int? CostCode11Id { get; set; }
        public double? CostCode11Percentage { get; set; }
        public int? CostCode12Id { get; set; }
        public double? CostCode12Percentage { get; set; }
        public int? CostCode13Id { get; set; }
        public double? CostCode13Percentage { get; set; }
        public int? CostCode14Id { get; set; }
        public double? CostCode14Percentage { get; set; }
        public int? CostCode15Id { get; set; }
        public double? CostCode15Percentage { get; set; }
        public int? CostCode1Id { get; set; }
        public double? CostCode1Percentage { get; set; }
        public int? CostCode2Id { get; set; }
        public double? CostCode2Percentage { get; set; }
        public int? CostCode3Id { get; set; }
        public double? CostCode3Percentage { get; set; }



        public int? CostCode4Id { get; set; }
        public double? CostCode4Percentage { get; set; }
        public int? CostCode5Id { get; set; }
        public double? CostCode5Percentage { get; set; }
        public int? CostCode6Id { get; set; }
        public double? CostCode6Percentage { get; set; }
        public int? CostCode7Id { get; set; }
        public double? CostCode7Percentage { get; set; }
        public int? CostCode8Id { get; set; }
        public double? CostCode8Percentage { get; set; }
        public int? CostCode9Id { get; set; }
        public double? CostCode9Percentage { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public int? DepartmentId { get; set; }
        public DateTime? DirectorEndDate { get; set; }
        public DateTime? DirectorStartDate { get; set; }
        public string Email { get; set; }
        public string EmployeeNo { get; set; }
        public int? EmployeeTypeId { get; set; }
        public int? EmploymentBasisId { get; set; }
        public int? EthnicOriginId { get; set; }
        public bool? ExcludeOmniSlip { get; set; }
        public bool? ExcludePartPayments { get; set; }
        public bool? ExcludePayslipPrinting { get; set; }
        public bool? ExcludeSalarySacrifice { get; set; }
        public string Forename1 { get; set; }
        public string Forename2 { get; set; }
        public int? Gender { get; set; }
        public string Grade { get; set; }


        public int? GradeId { get; set; }
        public string HashKey { get; set; }
        public string HashValue { get; set; }
        public bool? HasP11d { get; set; }
        public bool? HasSMP1L { get; set; }
        public bool? HasSSP1L { get; set; }
        public DateTime? HmrcJoinDate { get; set; }
        public int Id { get; set; }
        public string Initials { get; set; }
        public bool? IsDead { get; set; }
        public bool? IsDeleted { get; set; }
        public bool? IsDirector { get; set; }
        public bool? IsEligibleWhileInScheme { get; set; }
        public bool? IsExpat { get; set; }
        public bool? IsInNICHoliday { get; set; }
        public bool? IsInPension { get; set; }
        public bool? IsIrregular { get; set; }
        public bool? IsKnownAsDirector { get; set; }
        public bool? IsNewEmployee { get; set; }
        public bool? IsPeriodPayMethod { get; set; }
        public bool? IsPostLeavingPayment { get; set; }
        public bool? IsPostP45Pay { get; set; }
        public bool? IsPreRun { get; set; }
        public bool? IsReRun { get; set; }
        public bool? IsRun { get; set; }
        public bool? IsShiftWorker { get; set; }
        public bool? IsStudentLoan { get; set; }
        //public bool? IsSuspended { get; set; }
        public bool? IsUkWorker { get; set; }
        public string JobTitle { get; set; }

        public int? JobTitleId { get; set; }
        public DateTime? JoinDate { get; set; }
        public string KnownAs { get; set; }
        public string LastPaidPeriod { get; set; }
        public double? LeaveBalance { get; set; }
        public double? LeaveDue { get; set; }
        public string LeavePattern { get; set; }
        public double? LeaveTaken { get; set; }
        public double? LeaveThisYear { get; set; }
        public DateTime? LeavingDate { get; set; }
        public DateTime? LeftDate { get; set; }
        public bool? LeftNoPay { get; set; }
        public string LettersAfterName { get; set; }
        public int? MartialStatus { get; set; }
        public int? NationalityId { get; set; }
        public int? NILetter { get; set; }
        public string NINumber { get; set; }
        public bool? NIUptoLEL { get; set; }
        public string Notes { get; set; }
        public int? PayBasis { get; set; }
        public int? PayMethod { get; set; }
        public string PayPoint { get; set; }
        public int? PayrollType { get; set; }
        public DateTime? PensionStartDate { get; set; }
        public int? PeriodId { get; set; }
        public int? PersonnelStatusId { get; set; }
        public string PostToName { get; set; }
        public string PrevEmployeeNo { get; set; }
        public string PreviousSurname { get; set; }
        public bool? PrintZeroPayslip { get; set; }
        public DateTime? RetirementDate { get; set; }
        public string RtiEmployeeRef { get; set; }
        public string RtiSerialNo { get; set; }
        public string RunPeriodNumber { get; set; }
        public DateTime? SalaryEffectiveDate { get; set; }
        public int? SiteId { get; set; }
        public DateTime? StudentLoanEndDate { get; set; }
        public int? StudentLoanPlanType { get; set; }
        public DateTime? StudentLoanStartDate { get; set; }
        public string Surname { get; set; }
        public int? TaxBasis { get; set; }
        public string TaxCode { get; set; }
        public int? Title { get; set; }
        public int? UnionId { get; set; }
        public string UserData1 { get; set; }
        public string UserData10 { get; set; }
        public string UserData11 { get; set; }
        public string UserData12 { get; set; }
        public string UserData13 { get; set; }
        public string UserData14 { get; set; }
        public string UserData15 { get; set; }
        public string UserData16 { get; set; }
        public string UserData17 { get; set; }
        public string UserData18 { get; set; }
        public string UserData19 { get; set; }
        public string UserData2 { get; set; }
        public string UserData20 { get; set; }
        public string UserData21 { get; set; }
        public string UserData22 { get; set; }
        public string UserData23 { get; set; }
        public string UserData24 { get; set; }
        public string UserData25 { get; set; }
        public string UserData3 { get; set; }
        public string UserData4 { get; set; }
        public string UserData5 { get; set; }
        public string UserData6 { get; set; }
        public string UserData7 { get; set; }
        public string UserData8 { get; set; }
        public string UserData9 { get; set; }
        public double? WorkingDays { get; set; }
        public string WorkPattern { get; set; }
        public int? WorkType { get; set; }
        public string InternalPhone { get; set; }
        public string MobilePhone { get; set; }
        public string PersonalEmail { get; set; }
        public string WorkEmail { get; set; }
        public int? PayPointId { get; set; }
        public bool? IsApprentice { get; set; }
        public DateTime? ApprenticeshipStartDate { get; set; }
        public DateTime? ApprenticeshipEndDate { get; set; }
        public int? LeavePatternId { get; set; }
        public double? LeaveBroughtForward { get; set; }
        public int? FullPartTime { get; set; }
        public int? NoticePeriodId { get; set; }
        public DateTime? LastModifiedDate { get; set; }
        public string LastModifiedUser { get; set; }
        public DateTime? CreatedDate { get; set; }
        public string ServiceIndicator { get; set; }
        public int? PayrollStatus { get; set; }
        public int? PayrollId { get; set; }

       
    }
}
